# Generated by Django 4.2.6 on 2023-10-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_ranklist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ranklist',
            unique_together={('student_rank', 'report_card_date')},
        ),
    ]
